### ISSUE TITLE
How to display multiple documents independently?

### ISSUE THREAD

**Issue by gethob** [hasura/gatsby-gitbook-starter#119]
I tried the repository, it displays all the available markdown under content directory in just one document/tutorial. I could not find out if there is a way to configure it to have multiple books/tutorials and display the tutorials respectively like on hasura.io. Could you please share how to do that? thank you.

**Comment by praveenweb** [comment]
@gethob - At Hasura, we use individual instances of this starter for each tutorial. This way, each tutorial gets its own configuration file and everything is isolated. Are you looking at different ways of doing this?

**Comment by gethob** [comment]
@praveenweb  thank you very much for your quick reply. Actually it would be great to have multiple tutorials just by having markdown subdivided, based on the tutorial/topic name in different subdirectories of the folder "content". I can imagine how multiple instances could be helpful in terms of performance and flexibility though.
