### ISSUE TITLE
Build failing when parsing MDX

### ISSUE THREAD

**Issue by readywater** [hasura/gatsby-gitbook-starter#18]
Getting errors when attempting to build the application.
Specifically:

```
 ERROR #95313

Building static HTML failed for path "/modules/pl7505/1-discussion"

See our docs page for more info on this error: https://gatsby.dev/debug-html


   9 | /* eslint-disable react/display-name */
  10 | export default {
> 11 |   h1: props => <Heading id={props.children.replace(/\s+/g, '').toLowerCase()} {...props} is="h1" fontSize={[5, 6]} />,
     |                                            ^
  12 |   h2: props => <Heading id={props.children.replace(/\s+/g, '').toLowerCase()} {...props} is="h2" fontSize={[4]} />,
  13 |   h3: props => <Heading id={props.children.replace(/\s+/g, '').toLowerCase()} {...props} is="h3" fontSize={3} />,
  14 |   h4: props => <Heading id={props.children.replace(/\s+/g, '').toLowerCase()} {...props} is="h4" fontSize={2} />,


  WebpackError: TypeError: Cannot read property 'replace' of undefined
  - index.js:11 h1
    src/components/mdxComponents/index.js:11:44


⠸ Building static HTML for pages

```

The repo I'm trying to build is at: https://github.com/readywater/sec.andrewlb.com

And I'm trying to deploy it to gh-pages as well, though this is pre-deployment, as the failure is happening on the build phase.

**Comment by techtolentino** [comment]
@readywater 

The reason this isn't building properly is because there's an empty markdown `h1`, and I assume the build process is looking for some string at this point?

Look in your code here:
https://github.com/readywater/sec.andrewlb.com/blame/master/content/modules/pl7505/1-discussion.md#L7

**Comment by praveenweb** [comment]
@readywater - This usually happens when the heading tags (h1, h2 .., h6) are empty or if they have special characters like `, quoting the string in between.

**Comment by praveenweb** [comment]
I'm closing this for now. Feel free to reopen if it breaks for you in normal usage.
