### ISSUE TITLE
Can't import React component

### ISSUE THREAD

**Issue by lusa** [hasura/gatsby-gitbook-starter#19]
How can we import React components into mdx files? I tried a very simple example and it didn't work: 
```
---
title: "Button"
metaTitle: "Button Example"
metaDescription: "This is the meta description for this page"
---

import {Button} from './button'

Example of a button.

<Button/>
```

**Comment by 10chars** [comment]
@lusa I had the same problem.  You need to import in the `src/components/mdxComponents/index.js`file which is past to the MDXProvider's components prop in `src/components/layout.js`

**src/components/mdxComponents/index.js:**
```
import MyComponent from './MyComponent';
export default {
  /* other components */
  MyComponent
};
```

**inside your mdx content:**
```
<MyComponent />

```

**Comment by lusa** [comment]
That worked, thanks!
