### ISSUE TITLE
Left nav section resizing on menu selection 

### ISSUE THREAD

**Issue by i001962** [hasura/gatsby-gitbook-starter#24]
Left nav is resizing on menu selections. Creates a jumpy visual when moving from menu selection to another selection.

To see example go here:
https://learn.hasura.io/graphql/react/queries/2-create-query
then select the content below the 'queries' section.
screenshot
https://screencast.com/t/EtZLmTu5t

At first I thought it was the size of the TOC on the right but that's not the cause.

**Comment by praveenweb** [comment]
@i001962 - This seems to have been fixed in one of the recent updates to styles and emotion dependency updates.
