### ISSUE TITLE
Double image rendering

### ISSUE THREAD

**Issue by Nierusan** [hasura/gatsby-gitbook-starter#25]
Hi ! I'm trying your really nice theme for documentation and I've got an annoying issue with images inside a mdx file.

When I import an image, there's always a good and bad version at the same time and I don't know how to remove the bad one. 

Example :
[Image issue](https://ibb.co/7jfvZBZ)
[mdx file](https://ibb.co/DbRBBrr)

I'm trying to tools with the plugin, but didn't found any solutions yet..

Thank you

**Comment by gaboesquivel** [comment]
https://github.com/gatsbyjs/gatsby/issues/11280

**Comment by i001962** [comment]
@Nierusan I ran into the same issue and resolved it by updating gatsby-config.js
 ```
....
  'gatsby-plugin-styled-components',
  {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [ `gatsby-remark-images` ],
      }
    },
  {
    resolve: 'gatsby-plugin-mdx',
    options: {
      gatsbyRemarkPlugins: [
        {
          resolve: "gatsby-remark-images",
          options: {
            maxWidth: 1035
          }
        },
        {
          resolve: 'gatsby-remark-copy-linked-files'
        }
      ],
      extensions: [".mdx", ".md"]
    }
  },
  'gatsby-plugin-emotion',
....
```

**Comment by Nierusan** [comment]
Thank you very very very much !!!!
