### ISSUE TITLE
Sorting as you add new MD file

### ISSUE THREAD

**Issue by jugraj** [hasura/gatsby-gitbook-starter#26]
When you add a new MD file to `content` folder it gets appended to the bottom of the the sidebar, however the order of the `Back` and `Next` arrows is all messed up. 

The Back and Next arrows follow sorting alphabetically whereas the sidebar adds the navigation by order of file added. e.g.; in image below the order of nav is based by the sequence of files added:

![image](https://user-images.githubusercontent.com/242900/66664579-b4659c00-ec44-11e9-937c-d0eae1d5e98a.png)

But here the sequence of Back and Next arrow is not following the sidebar nav: I am in `Verification` and I have Back Button saying `Use SDK in Node`. 

![image](https://user-images.githubusercontent.com/242900/66665004-85035f00-ec45-11e9-94df-113cf151328f.png)

Is there a possibility to sort sidebar nav based by title alphabetically as followed in Next and Back arrows, without the need to update `forcedNavOrder`?

**Comment by i001962** [comment]
Do you get the same results after clearing the cache and rebuilding? 
I ran into some weirdness with prev/next as well as the leftnav ordering after restructuring content folder but all seems to work as designed after 
```
rm -rf public && rm -rf .cache
```

**Comment by jugraj** [comment]
Thanks @i001962 that seem to have fixed the issue! Just wondering if there can be a seamless release to tackle this issue :)

**Comment by praveenweb** [comment]
@jugraj - This happens due to Gatsby caching the content. If the entire structure is changed, i'm not sure the cache works. The seamless way would be to remove cache during major structure changes. `gatsby clean` would work for clearing the cache. May be you can package it in your npm script.
