### ISSUE TITLE
forcedNavOrder for dropdown

### ISSUE THREAD

**Issue by JGeiser9** [hasura/gatsby-gitbook-starter#56]
First, this is an awesome template for a docs page. Thanks for all of your hard work on this template. 

I skimmed through and attempted to edit the config.js file a bit after cloning for an option to force the order of the sub menu items as well. Is there a way to currently do this that I may have missed?

Thanks!

**Comment by praveenweb** [comment]
Hi @JGeiser9,

The forced ordering of nav items is currently configurable only for the top level items. For sub items, it is assumed that files will be ordered alphabetically. Typically number prefixes like 1, 1.1 etc are used to force the order.

**Comment by JGeiser9** [comment]
Thats a fair assumption, I will roll with the prefix format. Thanks for the response

**Comment by pdesmarets** [comment]
I love the template, thanks for making it available.  But renumbering when inserting a new page can be cumbersome and error prone.  It would be great to enhance the forcedNavOrder capability to declare the order of nested levels.

**Comment by pdesmarets** [comment]
Besides, it appears that the Contents right-hand sidebar is lost when naming files start with a number.
