### ISSUE TITLE
add search functionality

### ISSUE THREAD

**Issue by praveenweb** [hasura/gatsby-gitbook-starter#6]
The search should crawl through all the markdown files for content and give back the links to the pages of the content with possible highlighting of the searched word.

**Comment by coco98** [comment]
Or maybe have an algolia integration?

**Comment by praveenweb** [comment]
@elijah-io You don’t need to modify any code to get the Algolia search working. If the configuration is set correctly, all you need to do is to do a ‘npm run build’ once with the correct environment variables set and indexing should happen automatically. 
Have you tried running that step or is the index you are trying to use is different?

**Comment by theBliz** [comment]
@elijah-io did you close the issue because you were able to solve this? I'm having the same issue but probably I'm doing something wrong. How did you solve it?

**Comment by theBliz** [comment]
Nevermind. I figured it out.
Basically you need to do `npm run build` in order to set the index in algolia and then you can use it also locally. Might be cleared out in the readme, if I have time I'll make a pull request

**Comment by theBliz** [comment]
@praveenweb I've added a small section to quickly explain the steps needed for running algolia the first time. You can find it here https://github.com/hasura/gatsby-gitbook-starter/pull/43
