### ISSUE TITLE
Support for ordering sidebar by frontmatter: order?

### ISSUE THREAD

**Issue by monkey5an** [hasura/gatsby-gitbook-starter#91]
New to Gatsby, here's my question:

How can I set up this starter so that it sorts articles in sidebar by a frontmatter value, such as `order`, so that articles are not sorted alphabetically by title, which is hugely unhelpful in almost any documentation context.

**Comment by monkey5an** [comment]
The existing system works well enough, and I have since learned how to make the change myself if needed.

Thanks.

**Comment by swarupdonepudi** [comment]
@monkey5an could you please elaborate on what you have done to fix this default behavior of expanding all the sidebar items by default.

**Comment by donenoyes** [comment]
@monkey5an Can you share what code you changed for sort order?
